// js/decks.js

const GAME_DECKS = {
  playerDeck: {
    commander: { name: "Dina, Soul Steeper", type: "Legendary Creature", count: 1 },
    cards: [
      { name: "Dina, Essence Brewer", type: "Creature", count: 1 },
      { name: "Arcane Signet", type: "Artifact", count: 1 },
      { name: "Assassin's Trophy", type: "Instant", count: 1 },
      { name: "Awakening Zone", type: "Enchantment", count: 1 },
      { name: "Beledros Witherbloom", type: "Creature", count: 1 },
      { name: "Blight Mound", type: "Enchantment", count: 1 },
      { name: "Blood Artist", type: "Creature", count: 1 },
      { name: "Bloodghast", type: "Creature", count: 1 },
      { name: "Blossoming Bogbeast", type: "Creature", count: 1 },
      { name: "Bojuka Bog", type: "Land", count: 1 },
      { name: "Casualties of War", type: "Sorcery", count: 1 },
      { name: "Command Tower", type: "Land", count: 1 },
      { name: "Creakwood Liege", type: "Creature", count: 1 },
      { name: "Culling Ritual", type: "Sorcery", count: 1 },
      { name: "Cultivate", type: "Sorcery", count: 1 },
      { name: "Deadly Brew", type: "Sorcery", count: 1 },
      { name: "Defiling Daemogoth", type: "Creature", count: 1 },
      { name: "Eccentric Pestfinder", type: "Creature", count: 1 },
      { name: "Elvish Mystic", type: "Creature", count: 1 },
      { name: "Exotic Orchard", type: "Land", count: 1 },
      { name: "Fabled Passage", type: "Land", count: 1 },
      { name: "Feral Appetite", type: "Instant", count: 1 },
      { name: "Festering Thicket", type: "Land", count: 1 },
      { name: "Final Act", type: "Sorcery", count: 1 },
      { name: "Forest", type: "Basic Land", count: 8 },
      { name: "Gilded Goose", type: "Creature", count: 1 },
      { name: "Gorma, the Gullet", type: "Creature", count: 1 },
      { name: "Grim Backwoods", type: "Land", count: 1 },
      { name: "Gyome, Master Chef", type: "Creature", count: 1 },
      { name: "Haunted Mire", type: "Land", count: 1 },
      { name: "Haywire Mite", type: "Creature", count: 1 },
      { name: "High Market", type: "Land", count: 1 },
      { name: "Immoral Bargain", type: "Instant", count: 1 },
      { name: "Infernal Grasp", type: "Instant", count: 1 },
      { name: "Jadar, Ghoulcaller of Nephalia", type: "Creature", count: 1 },
      { name: "Llanowar Wastes", type: "Land", count: 1 },
      { name: "Mazirek, Kraul Death Priest", type: "Creature", count: 1 },
      { name: "Merchant of Venom", type: "Creature", count: 1 },
      { name: "Moldervine Reclamation", type: "Enchantment", count: 1 },
      { name: "Morbid Opportunist", type: "Creature", count: 1 },
      { name: "Mortality Spear", type: "Instant", count: 1 },
      { name: "Mycoloth", type: "Creature", count: 1 },
      { name: "Necroblossom Snarl", type: "Land", count: 1 },
      { name: "Nether Traitor", type: "Creature", count: 1 },
      { name: "Night's Whisper", type: "Sorcery", count: 1 },
      { name: "Ohran Frostfang", type: "Creature", count: 1 },
      { name: "Ominous Harvest", type: "Sorcery", count: 1 },
      { name: "Ophiomancer", type: "Creature", count: 1 },
      { name: "Path of Ancestry", type: "Land", count: 1 },
      { name: "Pawn of Ulamog", type: "Creature", count: 1 },
      { name: "Pest Infestation", type: "Sorcery", count: 1 },
      { name: "Pest Rescuer", type: "Creature", count: 1 },
      { name: "Plumb the Forbidden", type: "Instant", count: 1 },
      { name: "Priest of Forgotten Gods", type: "Creature", count: 1 },
      { name: "Ribtruss Roaster", type: "Creature", count: 1 },
      { name: "Sakura-Tribe Elder", type: "Creature", count: 1 },
      { name: "Smothering Abomination", type: "Creature", count: 1 },
      { name: "Sol Ring", type: "Artifact", count: 1 },
      { name: "Springbloom Druid", type: "Creature", count: 1 },
      { name: "Stensian Sanguinist", type: "Creature", count: 1 },
      { name: "Study Hall", type: "Land", count: 1 },
      { name: "Swamp", type: "Basic Land", count: 8 },
      { name: "Teacher's Pest", type: "Creature", count: 1 },
      { name: "Temple of Malady", type: "Land", count: 1 },
      { name: "Tendershoot Dryad", type: "Creature", count: 1 },
      { name: "Terramorphic Expanse", type: "Land", count: 1 },
      { name: "Titan's Grave", type: "Land", count: 1 },
      { name: "Toxic Deluge", type: "Sorcery", count: 1 },
      { name: "Trudge Garden", type: "Enchantment", count: 1 },
      { name: "Turbulent Fen", type: "Land", count: 1 },
      { name: "Twilight Mire", type: "Land", count: 1 },
      { name: "Umbral Collar Zealot", type: "Creature", count: 1 },
      { name: "Veinwitch Coven", type: "Creature", count: 1 },
      { name: "Vernal Fen", type: "Land", count: 1 },
      { name: "Viridescent Bog", type: "Land", count: 1 },
      { name: "Viscera Seer", type: "Creature", count: 1 },
      { name: "Wight of the Reliquary", type: "Creature", count: 1 },
      { name: "Witch of the Moors", type: "Creature", count: 1 },
      { name: "Witherbloom Campus", type: "Land", count: 1 },
      { name: "Witherbloom Charm", type: "Instant", count: 1 },
      { name: "Witherbloom Command", type: "Sorcery", count: 1 },
      { name: "Woe Strider", type: "Creature", count: 1 },
      { name: "Woodland Cemetery", type: "Land", count: 1 },
      { name: "Yahenni, Undying Partisan", type: "Creature", count: 1 },
      { name: "Zulaport Cutthroat", type: "Creature", count: 1 }
    ]
  }
};